### ISSUE TITLE
ValueError: Length mismatch

### ISSUE THREAD

**Issue by sdxsysu** [emdann/milopy#11] opened 2022-06-26 17:40 UTC
Hi,

I was running the code in the quick start from the tutorial section and this line milo.DA_nhoods(adata, design="~ condition")
 gave me this error: ValueError: Length mismatch: Expected axis has 5 elements, new values have 119 elements. I am wondering whether it's something wrong on my side. The weird thing is that I wrote a script with milopy a while ago that used to work fine but did not run through when I tried to re-run it today, giving me a similar error. Please let me know if you need more information.

Thanks

**Comment by emdann** [comment] 2022-06-26 19:21
Hi @sdxsysu, this error is caused by some update in the `rpy2` package, but it should be fixed since https://github.com/emdann/milopy/pull/8 
Could you try again after pulling the latest changes and reinstalling?

**Comment by sdxsysu** [comment] 2022-06-27 09:29
It's working now! Thanks!

**Closed** 2022-06-27 09:30 UTC
